# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/essential/mata/setup-makefiles.sh

AB_OTA_PARTITIONS += \
    abl \
    bluetooth \
    cmnlib \
    cmnlib64 \
    dsp \
    hyp \
    keymaster \
    modem \
    nvdef \
    rpm \
    tz \
    xbl

TARGET_RECOVERY_DEVICE_DIRS += vendor/essential/mata/proprietary
